name: Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push events for dev and main branches
  push:
    branches: [ dev, main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Deploy to DEV environment
  deploy-dev:
    name: Deploy to DEV
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to DEV using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP_HOST}}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/html/dev-blupy-core/
          git pull origin dev
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear

  # Deploy to PRODUCTION environment
  deploy-production:
    name: Deploy to PRODUCTION
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to PRODUCTION using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP_HOST_PROD }}
        username: ${{ secrets.USERNAME_PROD }}
        key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
        port: 22
        script: |
          cd /var/www/html/blupy-core/
          git pull origin main
          php artisan optimize:clear
          php artisan optimeze
          pm2 restart blupy-core-queue-worker